modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT License"
issueTrackerURL = "https://github.com/Mrthomas20121/Tinkers-Reforged/issues"

[[mods]]
modId = "tinkers_reforged"
version = "1.0.0"
displayName = "Tinkers Reforged"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/tinkers_reforged"
#logoFile="tinkers_reforged_logo.png"
credits = "Materialis and The Tinkers Devs for their help"
authors = "Mrthomas20121"
description = '''
Add new materials to Tinkers Construct
'''